/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    users: UserAuthOperations;
    'anonymous-users': AnonymousUserAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    users: User;
    'anonymous-users': AnonymousUser;
    accounts: Account;
    media: Media;
    reports: Report;
    topics: Topic;
    subtopics: Subtopic;
    indicators: Indicator;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      accounts: 'accounts';
      reports: 'reports';
    };
  };
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'anonymous-users': AnonymousUsersSelect<false> | AnonymousUsersSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    subtopics: SubtopicsSelect<false> | SubtopicsSelect<true>;
    indicators: IndicatorsSelect<false> | IndicatorsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es' | 'pt') | ('en' | 'es' | 'pt')[];
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'es' | 'pt';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | User | AnonymousUser;
  jobs: {
    tasks: {
      CleanAnonymousUsers: TaskCleanAnonymousUsers;
      CleanDraftReports: TaskCleanDraftReports;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AnonymousUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  image?: string | null;
  emailVerified?: string | null;
  communityOptIn?: boolean | null;
  accounts?: {
    docs?: (string | Account)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  reports?: {
    docs?: (string | Report)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  type: string;
  provider: string;
  providerAccountId: string;
  refreshToken?: string | null;
  accessToken?: string | null;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  title?: string | null;
  description?: string | null;
  user?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'anonymous-users';
        value: string | AnonymousUser;
      } | null);
  location:
    | {
        type: 'search';
        key: string | number;
        text: string;
        sourceIndex: number;
      }
    | {
        type: 'point' | 'multipoint' | 'polyline' | 'polygon' | 'extent' | 'mesh';
        geometry: {
          [k: string]: unknown;
        };
        buffer: number;
      };
  topics?:
    | {
        topic_id: number;
        description?: string | null;
        /**
         * What the report looked like when the AI summary was generated. Written by the app; the report editor compares it against the live report to offer a regeneration. See TopicSummaryStamp in app/(frontend)/parsers.ts.
         */
        description_stamp?: {
          indicator_ids?: number[];
          location_hash?: string | null;
        };
        indicators?:
          | {
              indicator_id: number;
              type: 'map' | 'chart' | 'table' | 'numeric' | 'custom' | 'ai';
              x: number;
              y: number;
              w: number;
              h: number;
              basemapId?:
                | (
                    | 'gray-vector'
                    | 'dark-gray-vector'
                    | 'satellite'
                    | 'streets'
                    | 'hybrid'
                    | 'osm'
                    | 'topo-vector'
                    | 'terrain'
                  )
                | null;
              opacity?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anonymous-users".
 */
export interface AnonymousUser {
  id: string;
  updatedAt: string;
  createdAt: string;
  collection: 'anonymous-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  /**
   * Numeric id from the original datum JSON. Referenced by existing reports rows and by the defaultTopics URL param. Never change it.
   */
  legacy_id: number;
  name: string;
  /**
   * Markdown. Rendered with react-markdown.
   */
  description?: string | null;
  /**
   * Path under client/public, e.g. /images/topics/territory.webp
   */
  image?: string | null;
  default_visualization?:
    | {
        indicator: string | Indicator;
        /**
         * The source data only uses map, numeric, chart and table; custom and ai exist to match Reports.
         */
        type: 'map' | 'chart' | 'table' | 'numeric' | 'custom' | 'ai';
        x: number;
        y: number;
        w: number;
        h: number;
        basemapId?:
          | (
              | 'gray-vector'
              | 'dark-gray-vector'
              | 'satellite'
              | 'streets'
              | 'hybrid'
              | 'osm'
              | 'topo-vector'
              | 'terrain'
            )
          | null;
        opacity?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicators".
 */
export interface Indicator {
  id: string;
  /**
   * Numeric id from the original datum JSON. Referenced by existing reports rows and by the defaultTopics URL param. Never change it.
   */
  legacy_id: number;
  /**
   * Display order within a subtopic. Not the same as legacy_id — they diverge on some rows.
   */
  order: number;
  subtopic: string | Subtopic;
  name: string;
  /**
   * e.g. km², m. Empty on 63 of 164 rows.
   */
  unit?: string | null;
  description_short: string;
  /**
   * Markdown. Rendered with react-markdown in containers/info.
   */
  description?: string | null;
  /**
   * Which widgets this indicator offers. Deliberately explicit, not derived: deriving would change 18 of 164 rows. Empty for all h3 indicators.
   */
  visualization_types?: ('map' | 'table' | 'chart' | 'numeric')[] | null;
  /**
   * Exactly one resource. The block type is the resource type.
   */
  resource: (
    | {
        /**
         * Display/machine name. Empty on 14 source rows; not read by any code for this resource type.
         */
        name?: string | null;
        url: string;
        /**
         * Text, not a number: lib/indicators.ts builds the layer URL as `url + layer_id`.
         */
        layer_id: string;
        /**
         * Rebuilt on read as { title, content: [{ type: 'fields', fieldInfos }] } — the only content shape present in the source data.
         */
        popupTemplate?: {
          title?: string | null;
          fieldInfos?:
            | {
                fieldName: string;
                label: string;
                id?: string | null;
              }[]
            | null;
        };
        /**
         * ArcGIS __esri.QueryProperties, passed unmodified to `new Query()`.
         */
        query_numeric?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * ArcGIS __esri.QueryProperties, passed unmodified to `new Query()`.
         */
        query_table?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * ArcGIS __esri.QueryProperties, passed unmodified to `new Query()`.
         */
        query_chart?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * ArcGIS __esri.QueryProperties, passed unmodified to `new Query()`.
         */
        query_ai?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'feature';
      }
    | {
        /**
         * Display/machine name. Empty on 14 source rows; not read by any code for this resource type.
         */
        name?: string | null;
        url: string;
        /**
         * ArcGIS __esri.RasterFunctionProperties, e.g. a Colormap function.
         */
        rasterFunction:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        legend: {
          type: 'basic';
          items: {
            label: string;
            /**
             * Hex, e.g. #EEF0BA
             */
            color: string;
            id?: string | null;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'imagery';
      }
    | {
        /**
         * Display/machine name. Empty on 14 source rows; not read by any code for this resource type.
         */
        name?: string | null;
        url: string;
        /**
         * ArcGIS __esri.RasterFunctionProperties, e.g. a Colormap function.
         */
        rasterFunction:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        legend: {
          type: 'basic';
          items: {
            label: string;
            /**
             * Hex, e.g. #EEF0BA
             */
            color: string;
            id?: string | null;
          }[];
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'imagery-tile';
      }
    | {
        /**
         * Display/machine name. Empty on 14 source rows; not read by any code for this resource type.
         */
        name?: string | null;
        url: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'web-tile';
      }
    | {
        /**
         * Machine name. Keys the COMPONENT_INDICATORS registry in containers/indicators/custom/index.tsx (`total-area`, `AMZ_LOCADM2`) — do not rename without checking that file.
         */
        name: string;
        /**
         * H3 variable name, matched against META.datasets[].var_name.
         */
        column: string;
        url?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'h3';
      }
    | {
        /**
         * Machine name. Keys the COMPONENT_INDICATORS registry in containers/indicators/custom/index.tsx (`total-area`, `AMZ_LOCADM2`) — do not rename without checking that file.
         */
        name: string;
        /**
         * ArcGIS __esri.QueryProperties, passed unmodified to `new Query()`.
         */
        query_ai?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'component';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subtopics".
 */
export interface Subtopic {
  id: string;
  /**
   * Numeric id from the original datum JSON. Referenced by existing reports rows and by the defaultTopics URL param. Never change it.
   */
  legacy_id: number;
  topic: string | Topic;
  /**
   * English only in the source data. ES and PT translations are seeded in phase 2; reads fall back to en until then.
   */
  name: string;
  /**
   * Markdown. Empty on every row in the source data.
   */
  description?: string | null;
  default_visualization?:
    | {
        indicator: string | Indicator;
        /**
         * The source data only uses map, numeric, chart and table; custom and ai exist to match Reports.
         */
        type: 'map' | 'chart' | 'table' | 'numeric' | 'custom' | 'ai';
        x: number;
        y: number;
        w: number;
        h: number;
        basemapId?:
          | (
              | 'gray-vector'
              | 'dark-gray-vector'
              | 'satellite'
              | 'streets'
              | 'hybrid'
              | 'osm'
              | 'topo-vector'
              | 'terrain'
            )
          | null;
        opacity?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  locale?: ('all' | 'en' | 'es' | 'pt') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: string;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'CleanAnonymousUsers'
          | 'CleanDraftReports'
          | 'createCollectionExport'
          | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | ('inline' | 'CleanAnonymousUsers' | 'CleanDraftReports' | 'createCollectionExport' | 'createCollectionImport')
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'anonymous-users';
        value: string | AnonymousUser;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'subtopics';
        value: string | Subtopic;
      } | null)
    | ({
        relationTo: 'indicators';
        value: string | Indicator;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'anonymous-users';
        value: string | AnonymousUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'admins';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'anonymous-users';
        value: string | AnonymousUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  emailVerified?: T;
  communityOptIn?: T;
  accounts?: T;
  reports?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anonymous-users_select".
 */
export interface AnonymousUsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  type?: T;
  provider?: T;
  providerAccountId?: T;
  refreshToken?: T;
  accessToken?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  user?: T;
  location?: T;
  topics?:
    | T
    | {
        topic_id?: T;
        description?: T;
        description_stamp?:
          | T
          | {
              indicator_ids?: T;
              location_hash?: T;
            };
        indicators?:
          | T
          | {
              indicator_id?: T;
              type?: T;
              x?: T;
              y?: T;
              w?: T;
              h?: T;
              basemapId?: T;
              opacity?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  legacy_id?: T;
  name?: T;
  description?: T;
  image?: T;
  default_visualization?:
    | T
    | {
        indicator?: T;
        type?: T;
        x?: T;
        y?: T;
        w?: T;
        h?: T;
        basemapId?: T;
        opacity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subtopics_select".
 */
export interface SubtopicsSelect<T extends boolean = true> {
  legacy_id?: T;
  topic?: T;
  name?: T;
  description?: T;
  default_visualization?:
    | T
    | {
        indicator?: T;
        type?: T;
        x?: T;
        y?: T;
        w?: T;
        h?: T;
        basemapId?: T;
        opacity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "indicators_select".
 */
export interface IndicatorsSelect<T extends boolean = true> {
  legacy_id?: T;
  order?: T;
  subtopic?: T;
  name?: T;
  unit?: T;
  description_short?: T;
  description?: T;
  visualization_types?: T;
  resource?:
    | T
    | {
        feature?:
          | T
          | {
              name?: T;
              url?: T;
              layer_id?: T;
              popupTemplate?:
                | T
                | {
                    title?: T;
                    fieldInfos?:
                      | T
                      | {
                          fieldName?: T;
                          label?: T;
                          id?: T;
                        };
                  };
              query_numeric?: T;
              query_table?: T;
              query_chart?: T;
              query_ai?: T;
              id?: T;
              blockName?: T;
            };
        imagery?:
          | T
          | {
              name?: T;
              url?: T;
              rasterFunction?: T;
              legend?:
                | T
                | {
                    type?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          color?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'imagery-tile'?:
          | T
          | {
              name?: T;
              url?: T;
              rasterFunction?: T;
              legend?:
                | T
                | {
                    type?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          color?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        'web-tile'?:
          | T
          | {
              name?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        h3?:
          | T
          | {
              name?: T;
              column?: T;
              url?: T;
              id?: T;
              blockName?: T;
            };
        component?:
          | T
          | {
              name?: T;
              query_ai?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanAnonymousUsers".
 */
export interface TaskCleanAnonymousUsers {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCleanDraftReports".
 */
export interface TaskCleanDraftReports {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'admins'
      | 'users'
      | 'anonymous-users'
      | 'accounts'
      | 'media'
      | 'reports'
      | 'topics'
      | 'subtopics'
      | 'indicators'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}