import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "admins_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "admins" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "admins" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "users_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "anonymous_users" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "anonymous_users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "accounts" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "accounts" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "accounts" ALTER COLUMN "user_id" SET DATA TYPE uuid;
  ALTER TABLE "media" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "media" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "reports_topics" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "reports" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "reports" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "reports_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "reports_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "reports_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "reports_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_version_topics_indicators" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_version_topics_indicators" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_version_topics_indicators" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_reports_v_version_topics" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_version_topics" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_version_topics" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_reports_v_version_topics_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_reports_v" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_locales" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "_reports_v_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "admins_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "accounts_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "media_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "reports_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "payload_jobs_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "admins_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_jobs_stats" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_jobs_stats" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "admins_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "admins" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "admins" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "users_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "anonymous_users" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "anonymous_users" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "accounts" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "accounts" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "accounts" ALTER COLUMN "user_id" SET DATA TYPE integer;
  ALTER TABLE "media" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "media" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "reports_topics" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "reports" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "reports" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "reports_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "reports_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "reports_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "reports_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v_version_topics_indicators" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v_version_topics_indicators" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_reports_v_version_topics_indicators" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_reports_v_version_topics" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v_version_topics" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_reports_v_version_topics" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_reports_v_version_topics_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_reports_v" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_reports_v" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v_locales" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "_reports_v_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "admins_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "accounts_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "media_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "reports_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "payload_jobs_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "admins_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "anonymous_users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_jobs_stats" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_jobs_stats" ALTER COLUMN "id" DROP DEFAULT;`)
}
