import random

tile_var_names = [
    "ASQKM",
    "ALTMEAN",
    "SLOMEAN",
    "TREECOV",
    "SHRUBLND",
    "GRASSLND",
    "CROPLND",
    "BUILDUP",
    "BARESPARS",
    "SNOW",
    "WATER",
    "HERBWTLN",
    "MANGROV",
    "MOSSLICHEN",
    "SPCOUNT",
    "MEANtonha",
    "FPCOUNT",
    "PPAMMEAN",
    "MATMEAN",
    "POP_E2030",
    "POP_E2025",
    "POP_E2015",
    "POP_E2000",
    "POP_E1975",
    "DIF30_75",
    "LENGHT",
    "DENSROAD",
    "FXavd_kbps",
    "MOavd_kbps",
    "PORCINDZ",
    "DEPINDMEAN",
    "URBPERC",
    "BUILDCOUNT",
    "BUIILDDENS",
    "CASS_PROD_Ha",
    "COCO_PROD_Ha",
    "COFF_PROD_Ha",
    "MAIZ_PROD_Ha",
    "OILP_PROD_Ha",
    "RICE_PROD_Ha",
    "RUBB_PROD_Ha",
    "SORG_PROD_Ha",
    "SOYB_PROD_Ha",
    "SUGC_PROD_Ha",
    "TOT_PROD_Ha",
    "CLOSE2MAINRIVER",
    "KBA_PERC",
    "EXTHEATCAT",
    "DRYMONTHCAT",
    "HOSPTIME7AM",
    "COASTCAT",
    "PERC_T11",
    "PERC_T14",
    "PERC_T42",
    "PERC_T71",
    "PERC_T72",
    "PERC_TF11",
    "PERC_TF13",
    "PERC_TF14",
    "DEFORPR00TO24",
    "FORSTPR24",
    "YOUHT1524",
    "WOMENPOP",
    "MENPOP",
    "ELDER60P",
    "UNDER5POP",
    "WOMREPAGE",
    "GRASSLANDT",
    "CANOPYHEIGTH",
    "RFLOODRSK",
    "UNESCODST",
    "BRIDGES",
    "GDWBARRIERS",
    "GDWRESERVOIRS",
    "GLOBENERGY",
    "HYDROELECT",
    "ILEGMINING",
    "FIREFIGRESCU",
    "INTBOCROSS",
    "MIGCUSTNET",
    "MILINSTAL",
    "POLICEINSTAL",
    "OILAREAP",
    "CELLTOWRS",
    "SPTSTFIX",
    "SPTSTMOB",
]


def get_query_params_with_random_columns(num_columns: int = 1) -> str:
    var_names = random.sample(tile_var_names, num_columns)
    query_params = "&".join(f"columns={var}" for var in var_names)
    return query_params
