import {
  countHardLineBreaks,
  extractMarkdownLinks,
  extractRichTextLinks,
  extractRichTextText,
} from "./markdown";
import type { RichText } from "./markdown";

/**
 * Compares a description's appearance before and after conversion, so a person
 * signs off on every field whose rendering changes.
 *
 * "Before" is what react-markdown renders today: CommonMark, no remark-gfm.
 * The comparison is deliberately narrow and computable rather than a full
 * re-implementation of two renderers — it checks the things that actually go
 * wrong in this content: hyperlinks disappearing, hard line breaks vanishing,
 * and formatting characters surfacing as literal text.
 */

export type FidelityIssue =
  | { kind: "links-lost"; urls: string[] }
  | { kind: "hard-line-breaks-lost"; count: number }
  | { kind: "literal-backslash"; sample: string }
  | { kind: "literal-asterisk"; sample: string };

export type FidelityFinding = {
  /** For example `indicator 42 description_es`. */
  where: string;
  issues: FidelityIssue[];
  before: string;
  after: string;
};

const sample = (text: string, pattern: RegExp): string | undefined => {
  const match = pattern.exec(text);
  if (!match) return undefined;

  const start = Math.max(0, match.index - 40);
  return text
    .slice(start, match.index + 40)
    .replace(/\s+/g, " ")
    .trim();
};

export const compareFidelity = ({
  where,
  markdown,
  richText,
}: {
  where: string;
  markdown: string;
  richText: RichText;
}): FidelityFinding | undefined => {
  const issues: FidelityIssue[] = [];

  const expectedLinks = extractMarkdownLinks(markdown);
  const actualLinks = new Set(extractRichTextLinks(richText));
  const lost = expectedLinks.filter((url) => !actualLinks.has(url));

  if (lost.length) {
    issues.push({ kind: "links-lost", urls: [...new Set(lost)] });
  }

  const breaks = countHardLineBreaks(markdown);
  if (breaks > 0) {
    issues.push({ kind: "hard-line-breaks-lost", count: breaks });
  }

  const after = extractRichTextText(richText);

  const backslash = sample(after, /\\/);
  if (backslash) {
    issues.push({ kind: "literal-backslash", sample: backslash });
  }

  // A lone asterisk left in the text means emphasis markers did not pair up in
  // the source, so they render literally instead of as emphasis.
  const asterisk = sample(after, /\*/);
  if (asterisk) {
    issues.push({ kind: "literal-asterisk", sample: asterisk });
  }

  if (!issues.length) return undefined;

  return { where, issues, before: markdown, after };
};

const describe = (issue: FidelityIssue): string => {
  switch (issue.kind) {
    case "links-lost":
      return `**${issue.urls.length} hyperlink(s) lost**: ${issue.urls.join(", ")}`;
    case "hard-line-breaks-lost":
      return `${issue.count} hard line break(s) folded into running text (no line break survives conversion)`;
    case "literal-backslash":
      return `literal backslash in output: \`${issue.sample}\``;
    case "literal-asterisk":
      return `literal asterisk in output: \`${issue.sample}\``;
  }
};

const truncate = (text: string, limit = 600): string =>
  text.length <= limit ? text : `${text.slice(0, limit)}\n…[truncated]`;

export type ReportContext = {
  counts: { topics: number; subtopics: number; indicators: number };
  droppedLayoutEntries: { owner: string; indicatorId: number }[];
  /** Owners left with no default layout at all once dead entries were dropped. */
  emptiedLayouts: string[];
  /** Known content problems this transform deliberately does not fix. */
  knownContentIssues: string[];
};

export const renderFidelityReport = (
  findings: FidelityFinding[],
  context: ReportContext,
): string => {
  const byKind = findings.reduce<Record<string, number>>((acc, finding) => {
    for (const issue of finding.issues) {
      acc[issue.kind] = (acc[issue.kind] ?? 0) + 1;
    }
    return acc;
  }, {});

  const lines: string[] = [
    "# Content migration fidelity report",
    "",
    "Generated by `pnpm transform-content` (AM-667). Every description whose",
    "appearance changes when converted from markdown to rich text is listed here",
    "for sign-off before the content is loaded into the CMS.",
    "",
    "## What was converted",
    "",
    `- Topics: ${context.counts.topics}`,
    `- Subtopics: ${context.counts.subtopics}`,
    `- Indicators: ${context.counts.indicators}`,
    "",
    "## Summary of differences",
    "",
  ];

  if (!findings.length) {
    lines.push("No description changes appearance. Nothing to review.", "");
  } else {
    lines.push(`${findings.length} description field(s) differ.`, "");
    for (const [kind, count] of Object.entries(byKind).sort((a, b) => b[1] - a[1])) {
      lines.push(`- \`${kind}\`: ${count}`);
    }
    lines.push("");
  }

  if (context.droppedLayoutEntries.length) {
    lines.push(
      "## Dropped layout entries",
      "",
      "Default-layout tiles pointing at an Indicator that does not exist. These",
      "render as nothing today, so removing them changes no behaviour.",
      "",
    );
    for (const entry of context.droppedLayoutEntries) {
      lines.push(`- ${entry.owner} → Indicator ${entry.indicatorId} (not in the catalogue)`);
    }
    lines.push("");
  }

  if (context.emptiedLayouts.length) {
    lines.push(
      "## Left with no default layout",
      "",
      "Every tile in these layouts pointed at a missing Indicator, so after the",
      "dead entries are dropped there is nothing left. They render as empty today",
      "too, but confirm that an empty default layout is acceptable here.",
      "",
    );
    for (const owner of context.emptiedLayouts) {
      lines.push(`- ${owner}`);
    }
    lines.push("");
  }

  if (context.knownContentIssues.length) {
    lines.push(
      "## Known content problems, not changed here",
      "",
      "These exist in the source content today. They are editorial fixes to make",
      "in the CMS after the migration (AM-671), not conversion artefacts.",
      "",
    );
    for (const issue of context.knownContentIssues) {
      lines.push(`- ${issue}`);
    }
    lines.push("");
  }

  if (findings.length) {
    lines.push("## Fields to review", "");

    for (const finding of findings) {
      lines.push(`### ${finding.where}`, "");
      for (const issue of finding.issues) {
        lines.push(`- ${describe(issue)}`);
      }
      lines.push(
        "",
        "<details><summary>Before (markdown source)</summary>",
        "",
        "```markdown",
        truncate(finding.before),
        "```",
        "",
        "</details>",
        "",
        "<details><summary>After (converted text)</summary>",
        "",
        "```text",
        truncate(finding.after),
        "```",
        "",
        "</details>",
        "",
      );
    }
  }

  return lines.join("\n");
};
